### ISSUE TITLE
请问如何使用这个脚本？

### ISSUE THREAD

**Issue by ScienceZone** [tianze0926/scripts#1]
您好，看到这个脚本似乎可以下载××学堂的书，请问在可以全文浏览的情况下如何使用你提供的脚本下载？急需下载一本书学习，网页极不方便也无法做笔记什么的，所以想着是否可以下载，网上的方法似乎现在都不可行了，在你这似乎看到了希望。方便的时候麻烦回复一下，谢谢！

**Comment by tianze0926** [comment]
我这个只适用于 lib-tsinghua.wqxuetang.com，不太了解其他站点的鉴权方式，你是用的哪个站点呢？

**Comment by ScienceZone** [comment]
就这个，或者书局那个，怎么用啊？能否稍微讲解一些？谢谢！

**Comment by tianze0926** [comment]
把代码中的下面这三个变量改成想要下载的书的信息，比如
```python
BOOK_ID = '5611' # 阅读界面 url 的末尾，例如 https://lib-tsinghua.wqxuetang.com/read/pdf?bid=5611
PAGE_NUM = 448 # 书共有多少页，阅读界面可以找到
NAME = 'math' # used as images directory name & pdf name，要提前手动创建好这个文件夹
```
然后用 Jupyter 运行即可
